branches:
  only:
  - develop
sudo: required
services:
- docker
env:
  global:
  - secure: fyHO71oPm3qViIMa8ANJR6kvocS6BqPsP0MM0LQVMBlpeK/2xe1zuEDgehrhqP3+os3HOX/JW/dntnZDGU83rvHC626PZQY3vGt1NAJtx+oYZDhZTn7q/zgGJ2AYN1ibFx5sBtYjvXQKjft53j+q/hLhk5H5YHOfyLMQ3tTD8TfYEcpeTlseYcJBfm+r+HGOZTsnhjFGXpmYg+3WDQeQlR0AxejvlXKfrB84JkxLM1SNWrETglR+vi7iX2o2KzAX0IOiRDu8mr1IpWH9zRD8EDvGvXL067PyocflXLJTWG8lqZE+s3wGSc1wtpJk10x5J4EYBbUH+pbN20VRFmCIvRlLuPFQg0fe3wuVI4CU3FRIfSkEvsURIkQ7e1q/MKMVg8OaLV3pcSrxvCBVC/NDcvu/GWoXqRA4Z5eQDjFJav6XL6IA4PZmj/r+ienvVLaqw4WSNIoU20pQtOXng1+U9FNYh/yy07LAax4s94B+J1nHpfe9G0klKiOXWS8HzF36WulnpfuAx5mVOy6EE1Pj0DXlYRxMFGG71PrOwJmTM/DWLlFD+TMJkYJI7kmEep8OX+4SpnrbIwjS/NXYowwpFiIjELPf50juwom1uw78bWZHfZ43AuhjfsceHt9LnK91E8Xd2pIixZhn2omSS0DEAY8lxE8Nu0NC2hxijI3YR3E=
  - secure: VDOTukN8c5M5KzdD8+ZwhH5r4M2movkPp2zaBcSp2tQgAkLDxPXnCL9CqLGHeO/GE+vZhovOB3V/JELYLNKgiYd4bJHLVwxdXfRKy3BIz+iobsLUBoYjFFuef7hKufiZcfKOCAtafqnqZRphc3PKOr1VEwlZA5sXLs16VZttX4xLILfXyBy5i+pc5jJQoilfy1rmHJeRGZEBEVj5dn3dcYU6ElQSg6BP+OdNWzws+W2kDQh7SBiLI/4voD5dSjsBK7nqdYDXO41VJhEdj4+nE0hO15Qic9mUZ9CGceVjENQ9ca+jEhYyNE++ZLd7D0abTjfpDnUkAlGzOwowAodBx3HcDVlNkKeC1TiRmVDAz0GqgbrbB74ktTymkqznXU+ZEIluBQm4GlTOD+KSf9V34lT7TylLsSAyrXtXT83AfQVAB4ORTouuVNOuBir4fJi8goCa2TRJqRvlgOqfOuEylAzxQetdMRcCKxDIj5uHeIHa5NW0e8rCvx6ry+MxRR9596Za+dB0uhyjWr0m9x3AuzDoXOq6RLS/JxYY6v9nApoDYjuHosstqxki8WBS5E0vLeGOgzVBBE/gzZri5ouASpSjMDQZD5B8MFSeduQrUe4r29PnoMF7X4sCN/ScM4G/1YCGFiZxqN7f+2crlB415p4xxDfBIlH2331kmwjsPnQ=
  - secure: U2kL8ZzZ5En5olGgG6UhJxeUxklHxgS2M3P2RTacNHBf5QYd+ugPedjR4KekFNXVvmXD8ERKnjHJjQyIe6UnZ5sW5Ljukv31J48EfPZoiAbmVEPUlrIEVMTX6tIl5dX7Mx8Kt9S7jhX/ZfHGaqfTR47bpO+ZPnZUUmkhtb7AHC+gFYRRrUU1DGO19ICejjw0+Qi266ybGytUvZi0utnnywuq6bZTyZS1pB6Q+Hbcy8i7YLA1NIRMliQPg/buKfDm/Pvk98d+wYPZudAO2JIyuMbbXBDYyFoS7gljqqtAuMmrf061W8qNV5U2npqRLeJrayQSWrKoyVDuWgthKJxpLS0XqMxFecygI+qdtsTkpBYp28JMZXoVbZqhZC1goq/aSTRAuuZ/SRUtUVRYhxQF4FL99rQ/zk5rtRdp/CPL+2neRkLI+/nPA3oWWr0b8W1uyGNYrC9SklPMTmXhEyo3ltxdZR0om3AKTLKfFjI74A4AWap1Cy65mVEE/WeNL3QuEB26P3ZNyyc33Wfkv+xB61u4rehlSz1mczZLcT9QS9sQ1pOu7SP+2aATGNSrdxRlmhyiGAnOmJ5eFH5mn6zRt0XDLjSvurgiQ9u+uZSX2zrHnlXkZd+FDGND0ol59s1tkmcC8UAJOc6od2Yiuycfb6W0I38n6KjIfZvK+E8HoaU=
  matrix:
  - TAGS=5.4 SAPI=cli
  - TAGS=5.4 SAPI=fpm
  - TAGS=5.4 SAPI=apache
  - TAGS=5.5 SAPI=cli
  - TAGS=5.5 SAPI=fpm
  - TAGS=5.5 SAPI=apache
  - TAGS=5.6 SAPI=cli
  - TAGS=5.6 SAPI=fpm
  - TAGS=5.6 SAPI=apache
before_install:
- docker pull php:$TAGS-$SAPI
script:
- docker tag php:$TAGS-$SAPI quay.io/ganiutomo/docker-php-laravel:$TAGS-$SAPI
after_script:
- docker login -u $USERNAME -p $USERPASS -e $USERMAIL quay.io
- docker push quay.io/ganiutomo/docker-php-laravel:$TAGS-$SAPI
