branches:
  only:
    - develop

sudo: required

services:
  - docker

language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SAPI=cli
  - SAPI=fpm
  - SAPI=apache

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y php5-cli

script:
  - docker build -t ganiutomo/php:$TRAVIS_PHP_VERSION-$SAPI .
