branches:
  only:
    - develop

sudo: required

language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - docker

env:
  - TAGS=cli
  - TAGS=fpm
  - TAGS=apache

script: "docker build -t ganiutomo/php:$TRAVIS_PHP_VERSION-$TAGS ."
