branches:
  only:
    - develop

sudo: required

services:
  - docker

env:
  - TAGS=5.4
  - TAGS=5.5
  - TAGS=5.6

script:
  - docker build -t ganiutomo/php:{$TAGS} {$TAGS}/.
  - docker build -t ganiutomo/php:{$TAGS}/fpm {$TAGS}/fpm/.
  - docker build -t ganiutomo/php:{$TAGS}/apache/ {$TAGS}/apache/.
